services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: cafrunikuhn
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: data_plat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
